### ISSUE TITLE
Make Hugo Build Options Configurable

### ISSUE THREAD

**Issue by joshmossas** [ModiiMedia/contentful-hugo#43]
Hugo [Build Options](https://gohugo.io/content-management/build-options/#readout) allow you to disable a page from showing up in list pages or disabled it getting rendered as a single. Adding the ability to change this via the config would be good. 

I think headless content should probably have the following set as default. And then we would allow the ability for it to be overridden.
```yaml
_build:
    render: never
    list: never
    publishResources: never 
```
