### ISSUE TITLE
Unable to pull any data

### ISSUE THREAD

**Issue by panzacoder** [ModiiMedia/contentful-hugo#53]
Hi there,

Apologies if I'm missing something obvious here, but I've been unable to run this successfully. I have a config file set up, but when I run this it just says

```
---------------------------------------------
   Pulling Published Data from Contentful...
---------------------------------------------


---------------------------------------------
```
I did have to run a script to replace windows-based whitespace on the executable in order to get it to run, not sure if that's related.

**Comment by joshmossas** [comment]
Hey panzacoder can you provide a copy of your config?
Also can you share more details about your environment? (OS and Node Version)

**Comment by joshmossas** [comment]
> I did have to run a script to replace windows-based whitespace on the executable in order to get it to run, not sure if that's related.

Hmm the latest version runs fine on my MacBook Air. I'm wondering why you had to do this.

**Comment by joshmossas** [comment]
Oh I also just realized. In Contentful are your entries published? Or are they all still drafts? If you want to pull drafts and published content then you need to run `contentful-hugo --preview` since it only pulls published content by default.

**Comment by panzacoder** [comment]
Thanks for all the replies! Here's my info:
Config:
```
contentful:
     space: '[redacted]' # defaults to CONTENTFUL_SPACE env variable
     token: '[redacted]' # defaults to  CONTENTFUL_TOKEN env variable
     # previewToken: 'content-preview-token' # defaults to  CONTENTFUL_PREVIEW_TOKEN env variable
     environment: 'master' # defaults to "master"

repeatableTypes:
    # fetches all the entries of a content type and places them in a directory.
    # Generated files will be named after their Entry ID in Contentful.

    - id: blogPost
      directory: content/blog
      fileExtension: md
      mainContent: body
      resolveEntries: # resolves a reference or asset field to a specific property
          - field: categories
            resolveTo: fields.name
          - field: author
            resolveTo: fields.name 
```
Node Version: `v14.11.0`
OS: `MacOS 11.4`

The contentful instance is definitely published, I'm working on migrating frontend systems for a live site.
